---
apiVersion: v1
kind: Service
metadata:
  name: apache-nifi-headless
spec:
  type: {{ .Values.headless.type }}
  clusterIP: None
  ports:
  - port: {{ .Values.properties.httpPort }}
    name: http
  - port: {{ .Values.properties.clusterPort }}
    name: cluster
  selector:
    app: {{ include "apache-nifi.name" . | quote }}
    release: {{ .Release.Name | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: apache-nifi
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: nifi
  selector:
    app: {{ template "apache-nifi.name" . }}
    release: {{ .Release.Name }}
{{- if .Values.metrics.prometheus.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "apache-nifi.fullname" . }}-metrics
  labels:
    app: {{ include "apache-nifi.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  ports:
  - name: metrics
    port: {{ .Values.metrics.prometheus.port }}
    protocol: TCP
    targetPort: metrics
  selector:
    app: {{ template "apache-nifi.name" . }}
    release: {{ .Release.Name }}
  type: ClusterIP
  {{- end }}    