apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nifi
spec:
  gateways:
  - default/core-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /apache-nifi
    route:
    - destination:
         host: nifi
         port:
           number: 8080
